---
output: github_document
  html_preview: true
---

# ggmol

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggmol)
library(ChemmineR)
library(ggforce) ## for annotating plots
library(umap)
library(MASS) ## to create a 2d map
set.seed(1)
```

```{r}
example_set <- c(
Diazepam = "Diazepam",
Lorazepam = "Lorazepam",
Clonazepam = "Clonazepam",
Lisinopril = "Lisinopril",
Enalapril = "Enalapril",
Ramipril = "Ramipril"
#Quinapril = "Quinapril"
#Benazepril = "Benazepril"
)

x <- read.csv("/Users/francesco/datapool/git/BAT-drugs/data/in/GSE70138_Broad_LINCS_pert_info.txt", sep="\t")
w <- which(tolower(x$pert_iname) %in% tolower(names(example_set)))
example_set <- x[w, "canonical_smiles"]
#example_set <- gsub("\\\\|/", "", x[w, "canonical_smiles"])
names(example_set) <- x[w, "pert_iname"]
dups <- which(duplicated(names(example_set)))
if (any(dups)) example_set <- example_set[-dups]
chemms <- chemmol(smiles=new("SMIset", smilist=as.list(example_set)))
```

```{r}
tab <- data.frame(
  name = names(example_set),
  smiles = example_set
)

ggplot(tab, aes(0, 0, smiles=smiles, label=name, chemsize=.7)) +
  geom_chemmap()+
  theme_no_axes()+
  facet_wrap(~name)+
  theme(aspect.ratio=1)

```


```{r}
moldists <- dist(chemms)
fprints_2d <- sammon(moldists)$points
clusters <- kmeans(fprints_2d, 2)$cluster

tab <- data.frame(
  x = fprints_2d[,1],
  y = fprints_2d[,2],
  name = names(example_set),
  smiles = example_set,
  Cluster= as.factor(clusters)
)
```

## 2D embedding based on structural distance

```{r fig.height=6, fig.width=6}
ggplot(tab, aes(x, y, smiles=smiles, chemsize=.1)) +
  geom_mol(show_atoms=F)+
  theme_bw()+
  labs(title="ChemMap example")+
  lims(x=c(-100, 100), y=c(-35, 30))+
  geom_mark_ellipse(aes(colour=Cluster, smiles=NULL), expand = .07)+
  theme(aspect.ratio=1)
```


```{r fig.height=8, fig.width=8}
library(ggrepel)
ggplot(tab, aes(x, y, smiles=smiles, colour=Cluster, label=name, chemsize=.08)) +
  geom_mol(resolution=150, show_atoms=F)+
  labs(title="ChemMap example")+
  geom_label_repel( size=2.5, point.padding=30)+
  lims(x=c(-100, 100), y=c(-35, 30))+
  theme(aspect.ratio=1)
```
## Ranking molecules

```{r fig.height=6, fig.width=8}

ggplot(tab[order(scores),], aes(x=1:nrow(tab), y=sort(scores)+1, smiles=smiles,
                label=name, chemsize=.1, fill=Cluster)) +
  geom_bar(stat="identity")+
  geom_chemmap(y=sort(scores)+13, showatoms=F) +
  theme_classic()+
  labs(title="ChemMap example", y="Scores", x="Molecules")+
  ylim(0, 180)+
  theme(aspect.ratio=1)+
  scale_x_continuous(breaks=1:nrow(tab), labels=tab$name)
  #coord_flip()
```


## Molecules side by side

```{r fig.height=8, fig.width=8}
library(ggpmisc)


scores <- as.matrix(moldists)[1,]
  
ggplot(tab, aes(0, 0, smiles=smiles, colour=Cluster, label=name, chemsize=.9, resolution=300)) +
  geom_chemmap()+
  theme_no_axes()+
  geom_text(label=paste("Score:", round(scores, 3)),
            x=Inf, y=-Inf, vjust=-.5, hjust=1.1,
            size=2.5, colour="black")+
  facet_wrap(~name)+
  theme(aspect.ratio=1)
```











